# Generated by Django 5.0.3 on 2024-05-14 20:12

import django.db.models.deletion
import kr_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[kr_app.models.check_positive])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('expiration_date', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kr_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
